### PR TITLE
Bug fixes for 372884 & 403735 & 390824

### PR DESCRIPTION
**Pull request by roshan-shaikh**
Bug fixes for 372884 & 403735 & 390824

### CODE REVIEW

**Review by PrasannaEviden — APPROVED** [review]
Approved

**Review by tufanshn — CHANGES_REQUESTED** [review]
We have a change for enrolled not registered.

**Review by rakeshmamidala221 — APPROVED** [review]

**Review by tufanshn — COMMENTED** [review]
good to go

**Review by tufanshn — COMMENTED** [review]
Good to go for the deployment

**Review by tufanshn — APPROVED** [review]

**Pull request merged**
